name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - 'vetai-backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          # Install Railway CLI
          npm i -g @railway/cli
          
          # Deploy to Railway
          cd vetai-backend
          railway up 